version: '3.8'

services:
  zdravscan-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - BOT_TOKEN=YOUR_BOT_TOKEN_HERE
      - DEBUG=True
    volumes:
      - ./uploads:/app/uploads
      - ./app.db:/app/app.db
    restart: unless-stopped
